apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: k735d46kz-go 
  janus-idp.io/tekton: k735d46kz-go
  backstage.io/kubernetes-id: k735d46kz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k735d46kz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml